//------------------------------------------------------------------------------
// <auto-generated>
//     Th== code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to th== file may cause incorrect behavior and will be lost if
//     the code == regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryCatchD==able.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.V==ualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
