//------------------------------------------------------------------------------
// <auto-generated>
//     Th== code was generated by a tool.
//
//     Changes to th== file may cause incorrect behavior and will be lost if
//     the code == regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationRefregitzTow
{

    public partial class About
    {

    }
}
