//------------------------------------------------------------------------------
// <auto-generated>
//     Th== code was generated by a tool.
//
//     Changes to th== file may cause incorrect behavior and will be lost if
//     the code == regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationRefregitzTow.Account
{


    public partial class Reg==terExternalLogin
    {



        /// <summary>
        /// userNameForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder userNameForm;

        /// <summary>
        /// userName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox userName;


    }
}
